### ISSUE TITLE
question when Spliting Pocket

### ISSUE THREAD

**Issue by DM0815** [Saoge123/PocketFlow#10]
when conducting Spliting Pocket function. I want to use my **.pdb and **.sdf file. I met a error as foolows：
 we can not compute the atoms on the surface of protein, because pymol can not be imported
Traceback (most recent call last):
  File "produce1xc6.py", line 6, in <module>
    pocket_block, _ = SplitPocket._split_pocket_with_surface_atoms(pro, lig, dist_cutoff)
  File "/home/dmeng/protein/PocketFlow/pocket_flow/utils/process_raw.py", line 68, in _split_pocket_with_surface_atoms
    protein.compute_surface_atoms()
  File "/home/dmeng/protein/PocketFlow/pocket_flow/utils/ParseFile.py", line 465, in compute_surface_atoms
    pymol.cmd.load(self.pdb_file)
NameError: name 'pymol' is not defined
BTW, I installed your env file successfully and can run your code of Molecular generation. Can you give some suggestions. Thanks.

**Comment by DM0815** [comment]
when I conducted pip3 install pymol. It reminds that 
Requirement already satisfied: pymol in ****/envs/pocketflow/lib/python3.8/site-packages (2.4.1)

[notice] A new release of pip is available: 23.3.2 -> 24.2
[notice] To update, run: pip install --upgrade pip

**Comment by Saoge123** [comment]
Hi, sorry for reply late. It seems to be uncorrect installation of pymol. You can try: 'conda install -c schrodinger pymol' or the commands in https://anaconda.org/schrodinger/pymol
