### ISSUE TITLE
KeyError:  'OG1'

### ISSUE THREAD

**Issue by indazole** [Saoge123/PocketFlow#8]
Hello,
Thank you for posting your code - nice work!
I have installed and tested, with success, a few of the sample pocket pdbs.
When trying to generate my own pocket pdb files, I run into the following error:

PocketFlow# python create_pocket_pdb.py --protein test.pdb --ligand test_lig.sdf 
 PyMOL not running, entering library mode (experimental)
Traceback (most recent call last):
  File "create_pocket_pdb.py", line 32, in <module>
    main()
  File "create_pocket_pdb.py", line 25, in main
    pocket_block, _ = SplitPocket._split_pocket_with_surface_atoms(
  File "/PocketFlow/pocket_flow/utils/process_raw.py", line 68, in _split_pocket_with_surface_atoms
    protein.compute_surface_atoms()
  File "/PocketFlow/pocket_flow/utils/ParseFile.py", line 480, in compute_surface_atoms
    res.atom_dict[a.name].is_surf = True
KeyError: 'OG1'

Any help is appreciated.

**Comment by Saoge123** [comment]
Hi, the error is lead by dismatching between the atom names of residues in your pdb and those at line 37 in utils/residues_base.py.

**Comment by indazole** [comment]
Ah, yes!  Missing atoms.  Thank you.
